org: mrbearclaw
app: shortbot
service: shortbot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  shortbot:
    handler: handler.shortbot
    events:
      - http:
          path: million-bot
          method: post
          cors: true
